name: React app deployment

on: workflow_dispatch

jobs:
  build-and-deploy:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Run deploy command
      run: npm run deploy