name: React app deployment

on: push

jobs:
  build-and-deploy:
    
    runs-on: ubuntu-latest
    env: 
      RSA_KIRAN: ${{ secrets.RSA_KIRAN }}
    
    steps:
    - uses: actions/checkout@v2

    - name: Cache node modules
      id: cache-node-modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: node_modules_cache
        restore-keys: node_modules_cache

    - name: Install node dependencies
      run: npm install

    - name: Setup SSH and Git config
      run: |
        sh github_actions.sh
        git remote -v

    - name: Run deploy command
      run: npm run deploy