name: React app deployment

on: push

jobs:
  build-and-deploy:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Cache node modules
      id: cache-node-modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: node_modules_cache
        restore-keys: node_modules_cache

    - name: Install node dependencies
      run: npm install

    - name: Setup Git remote
      env:
        USERNAME: kiir33
        PA_TOKEN: ${{ secrets.PA_TOKEN }}
      run: |
        git config user.name 'GitHub CI'
        git config user.email 'kiranbanmala3@gmail.com'
        git remote set-url origin https://${USERNAME}:${PA_TOKEN}git@github.com:${USERNAME}/Test.git
        git remote -v

    - name: Run deploy command
      run: npm run deploy